
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - backend

  auth:
    build: 
      context: ./auth
      dockerfile: Dockerfile
    container_name: auth-service
    depends_on:
      - mongo
    volumes:
    - ./auth:/app
    networks:
      - backend

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: gateway-service
    ports:
      - "3000:3000"
    environment:
      - AUTH_SERVICE_URL=http://auth-service:5000
    depends_on:
      - auth
    networks:
      - backend

volumes:
  mongo-data:

networks:
  backend:
    driver: bridge
