services:
  mongo-auth:
    image: mongo:latest
    container_name: mongo-auth
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - backend

  auth:
    build: 
      context: ./auth
      dockerfile: Dockerfile
    container_name: auth-service
    depends_on:
      - mongo-auth
    volumes:
    - ./auth:/app
    - /app/node_modules
    env_file:
      - ./auth/.env
    networks:
      - backend

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: gateway-service
    ports:
      - "3000:3000"
    volumes:
      - ./gateway:/app
      - /app/node_modules
    env_file:
      - ./gateway/.env
    depends_on:
      - auth
    networks:
      - backend

volumes:
  mongo-data:

networks:
  backend:
    driver: bridge